### ISSUE TITLE
Semigroup instance for Policy

### ISSUE THREAD

**Issue by Profpatsch** [scotty-web/wai-middleware-static#15]
It’s nice if you can use `(<>)`.

**Comment by RyanGlScott** [comment]
Fixed in https://github.com/scotty-web/wai-middleware-static/commit/8c967f616656c24f305b3a8e613002f4dae484a5. I've uploaded [`wai-middleware-static-0.8.1`](http://hackage.haskell.org/package/wai-middleware-static-0.8.1) to Hackage, which includes this change.

**Comment by Profpatsch** [comment]
Thanks!
