### ISSUE TITLE
not building under ghc 7.10.1

### ISSUE THREAD

**Issue by elfeck** [scotty-web/wai-middleware-static#6]
It seems that  filepath (>=1.3.0.1 && <1.4) breaks this package under ghc 7.10.1.
Could you update this requirement and/or fix issues that arise from that?

**Comment by RyanGlScott** [comment]
This is addressed by pull request #5.

I'd like to have this updated too—right now, it's preventing [`kansas-comet`](https://travis-ci.org/ku-fpg/kansas-comet/jobs/58822887#L627) from building correctly on GHC 7.10.

**Comment by RyanGlScott** [comment]
Luckily, he agreed to give me push permissions! I just uploaded a GHC 7.10-compatible release (`wai-middleware-static-0.7.0.0`) to Hackage.
